Repository canmet-energy/btap_ml, pull requests merged in 2021-11, with the labels that each got.

#12 Scaffolding
  .pre-commit-config.yaml
  README.md
  docs/installation.rst
  requirements-dev.txt
  requirements.txt
  src/config.py
  src/feature_selection.py
  src/predict.py
  src/preprocessing.py
Labels: enhancement

#14 Epw processing
  docs/data_prep/weather.rst
  docs/index.rst
  docs/installation.rst
  requirements.txt
  src/config.py
  src/prepare_weather.py
Labels: documentation, enhancement

#19 Parquet weather
  src/preprocessing.py
Labels: enhancement

#21 Fix link to DAaaS and ref aaw setup.
  docs/installation.rst
Labels: documentation

#23 Add src directory for automodule indexing.
  docs/conf.py
  docs/index.rst
  src/config.py
  src/plot.py
Labels: documentation

#24 Docs cleanup
  docs/conf.py
  docs/data_prep/weather.rst
  docs/index.rst
Labels: documentation

#30 Add digraph of process flow
  .github/workflows/docs.yml
  docs/index.rst
Labels: documentation

#36 Generate API docs
  docs/api/config.rst
  docs/api/feature_selection.rst
  docs/api/plot.rst
  docs/api/predict.rst
  docs/api/prepare_weather.rst
  docs/api/preprocessing.rst
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  src/config.py
  src/predict.py
  src/prepare_weather.py
  src/preprocessing.py
Labels: documentation

#39 updated the docs for the .rst files and also including tracing for the src files
  Dockerfile
  docs/usage/build_model.rst
  docs/usage/feature_selection.rst
  docs/usage/preprocessing.rst
  pipeline/create-pipeline.py
  pipeline/pipeline.py
  pipeline/pipeline.yaml
  pipeline/run.py
  pipeline/upload-pipeline.py
  pipeline/yaml/feature_selection.yml
  pipeline/yaml/predict.yml
  pipeline/yaml/preprocessing.yml
  src/config.py
  src/feature_selection.py
  src/predict.py
  src/preprocessing.py
Labels: documentation, enhancement

#42 resolve failing docs build
  src/config.py
  src/plot.py
  src/prepare_weather.py
  src/preprocessing.py
Labels: documentation
